module.exports = {
  maxHostCount:10,
  mallurl:"dddd",
  helpQQ:"QQ群:1010017806",
  helpEmail:"fishdivetechnology@gmail.com",
  homePage:"https://github.com/fishdivetechnology/home/wiki",
  chromeLink:"https://github.com/fishdivetechnology/home/wiki",
  praiceLink:"",
  payUrl:"http://pay.liguaika.xyz:3000/order",
  payToken:"q02PLH5Q",
  appID:"Owy2e3E",
  emall:"fishdivetechnology@gmail.com",
  smtp:"smtp.gmail.com",
  password:"fishDiveyibo.c.c.c",
  netIP:"172.105.116.57",
  tryDay:5,
}
